language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia docs/make.jl
  - julia -e 'cd(Pkg.dir("Documenter", "test")); include("coverage.jl")'
