language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

before_install:
  - echo "woot" && echo "boot"

after_success:
  - echo "woot" && julia -e 'cd(Pkg.dir("Documenter", "test")); include("coverage.jl")'
