language: julia

os:
  - linux
#  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia --color=yes ${TRAVIS_BUILD_DIR}/test/coverage.jl

jobs:
  include:
    - stage: "Deploy docs"
      #if: (branch = master) OR (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$) # only run deploy phase on master or when a version is being tagged
      julia: nightly
      os: linux
      script: julia --color=yes -e 'Pkg.clone(pwd())'
        && julia --color=yes -e 'Pkg.build("Documenter")'
        && julia --color=yes docs/make.jl deploy
      after_success: skip # don't submit coverage for docs
