language: julia

os:
  - linux
#  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia --color=yes test/coverage.jl

jobs:
  include:
    - stage: "Deploy docs"
      julia: nightly
      os: linux
      script: julia --color=yes -e 'Pkg.clone(pwd())'
        && julia --color=yes -e 'Pkg.build("Documenter")'
        && julia --color=yes docs/make.jl deploy
