var DOC_VERSIONS = [
  "monospace-size",
  "mobile-css-deploy",
  "mh-fix-nav-large",
  "mh-fix-nav",
  "latex-error",
  "latest",
  "hide",
  "gh-pages",
  "fork-debug-build",
  "fix-style",
  "bundle-highlightjs-deploy",
  "bug-relcontents",
  ".git",
  "release-0.10-deploy",
];
